### ISSUE TITLE
[화면연결/로직] 식물신분증 화면 연결

### ISSUE THREAD

**Issue by 1006lem** [BanApp/BeMyPlant_App#12]
## 전제 사항
- 식물 신분증 UI 생성 #9 

## 참고 화면
```
- 화면: (a) activity_main.xml (메인화면), (b) *activity_plant_id_card.xml (식물 신분증), (c) (식물 이미지 재선택창)
 
    (a) BeMyBlant/app/src/main/res/layout/activity_main.xml,
    (b) BeMyBlant/app/src/main/res/layout/activity_plant_id_card.xml

- 로직: (a)  MainActivity.kt (메인화면), (b) *PlantIDCardActivity.kt(식물 신분증) , (c) (식물 이미지 재선택창)
 
    (a) BeMyBlant/app/src/main/java/com/example/bemyplant/MainActivity.kt,
    (b) BeMyBlant/app/src/main/java/com/example/bemyplant/PlantIDCardActivity.kt,


* 가제 (구현 전)
```

(a) 메인 화면
<img width="150" alt="image" src="https://github.com/BanApp/BeMyPlant_App/assets/68532437/3b647fcb-d01f-4662-ba2c-2145bccb1868">

<br>

(b) 식물 신분증
<img width="150" alt="image" src="https://github.com/BanApp/BeMyPlant_App/assets/68532437/62909ce1-4984-4ad4-8186-cd860593c6b0">

<br>

(c) 식물 이미지 재선택창
<img width="150" alt="image" src="https://github.com/BanApp/BeMyPlant_App/assets/68532437/786441c1-9b65-40dd-93b8-b82376630f6a">

---

## 구현 사항

- (a) 메인 화면 -> 식물 이미지(imageView_main_flower) 클릭 시 -> (b) 식물 신분증으로 activity 연결 
- (b) 식물 신분증 -> (식물 신분증 내 식물 이미지) 클릭 시 -> (c) 식물 이미지 재선택창 연결

**Comment by Minjeongc** [comment]
(a) 메인 화면 내 식물 이미지 클릭 시, 신분증 나오도록 구현 완료 (글자 위치 및 배경은 수정 예정)

![Screenshot_20230911_174122](https://github.com/BanApp/BeMyPlant_App/assets/87174310/ca462178-1a1b-4cd4-9292-8e2106eb5bf3)

**Comment by Minjeongc** [comment]
cmj2 브랜치에 우선 다 커밋해놨습니다 🥰🥰 
* FlowerIdFragment(식물신분증 파일명) 
* 식물선택창 구현 완료 + 문구 수정만 아직 구현 X
* 식물 이미지 선택창 로직 수정 할 예정 
(구현해야하는 부분은 월요일까지 구현할게요~! ) 

-건의사항 
환경설정 팝업창 + 그 외의 팝업창 (ex. 다이어리 팝업/ 블루투스 팝업 등 )모두 하나의 폴더 내에 넣어놔도 될까요?

**Comment by 1006lem** [comment]
변경사항 확인했습니다 !! 👍👍굳굳 !!! 
팝업창 굉장히 예쁘네요 수고 많으셨습니다 ㅜㅜ 

- 오 건의사항 아주 좋습니다 ! 팝업창 폴더 만들어서 그곳에서 관리하자는 것이죠?? 완전 찬성입니다 !! 굳굳

- cmj2, km 브랜치 중 충돌이 나는 부분은 구현이 모두 완료되고 진행합시다 ~! 
지금 db쪽에서 작업을 진행중인 것 같아서요 ! 
그럼 **현재 main으로 db 작업 -> (다음주) cmj, km 브랜치 통합 -> 추가적인 db작업 완료 (신분증)** 이런 느낌으로 괜찮을까요 !?

**Comment by Minjeongc** [comment]
네에~! 다음주에 DB연결하는 걸로!!
+ 환경설정 내 식물 삭제 -> popup -> 예 버튼 클릭 -> 메인 화면으로 이동 -> + 클릭 -> **식물 이미지 선택** ---부분에서 
'+' 클릭을 하면 **식물 이미지 선택 창 (imageSelect)** 로 넘어가는거 대신  **식물 등록 창 (plantRegister)** 로 넘어가서 센서 등록까지 하는걸로 수정하면 어떨까요?

**Comment by 1006lem** [comment]
오 !! plantRegister로 연결하는 것 아주 좋습니다!  
- 식물이 없고 -> (+) 버튼을 누른다면 -> **식물 등록창으로 연결 (plantRegister)** -> (nav_graph 흐름 참고)
- 식물이 있고 -> 식물 신분증에서 그림 선책 -> **식물 이미지 재선택창(imageReselect)** -> main
이 흐름 말씀이시죠? 아주 좋습니다 !~!~! bbb

**Comment by Minjeongc** [comment]
[device-2023-09-23-211213.webm](https://github.com/BanApp/BeMyPlant_Frontend/assets/87174310/bb05b471-462e-4f6b-85e2-6d4446bbb92c)

**- 구현한 부분**
ImageSelect은 구현했습니다! (조건에 따라 화면 전환(fragment,activity), 식물 이미지 변경시 문구 (hellotext)수정, 이미지 업데이트)


**- 구현해야 하는 부분** 

1. 식물 이름 설정후에 imageSelect에 식물 이름 업데이트 되게끔 구현해야 할거 같아요!
2. 식물 삭제 후 nav_graph 따라가는 부분은 계속 오류(nav_graph가 정의 되어있지 않다)가 생겨서 구현 방법좀 생각해 봐야할 거 같아요... 🥲 
3. 회원가입에서 눈 버튼에 따라 비밀번호 *처리하는 부분

**Comment by 1006lem** [comment]
오 방금 확인했습니다 !! bbb 
image  reselect까지 깔끔하게 구현해주셨네요 짱짱!! 수고 많으셨습니다 !!!bb

이제 km, cmj2 두 브랜치 합치는 작업 진행하겠습니다 잠시만 작업은 멈춰주시면 좋을 것 같습니다 !!

**Comment by 1006lem** [comment]
km, cmj2 브랜치 병합 완료했습니다 ! 

큰 변동 사항은 없고,
## conflict 나는 부분 (setting)
setting 부분에 있어서 popup 구현 시 

| branch | cmj2 | km |
| :---: | :---: | :---: |
| 구현 방식 | fragment 겹침 | AlterDialog|
| 팝업 시 동작코드 위치 | popup-fragment | settingActivity |
| 장점 | popup창 UI를 그대로 살릴 수 있음 | popup창 주변이 어두워지는 효과 | 


이때 popup의 UI 구성 (xml 파일)은 cmj2 브랜치의 것으로 따랐고, 
popup 시 동작코드 위치, popup효과는 km 브랜치의 것을 따르려 하였습니다 !

다만, UI부분에서 테두리를 넣으니 다음과 같이 팝업창(alterDialog제공) 규격과 맞지 않은 것이 두드러지게 나타납니다.
![image](https://github.com/BanApp/BeMyPlant_Frontend/assets/68532437/a8655f46-476e-4ac1-bf7e-8302ba996c69)

이러한 이유로, 
임의로 로그아웃/회원탈퇴/식물삭제 세 xml파일에서, **테두리만 없애** 적용했습니다 


(혹시 관련해서 의아한 점이나, 변경하고 싶은 점이 있다면 언제든 말씀해주세요 ~!)


## '구현해야 하는 부분' 리뷰

[바로 위에서 말씀해주신 '구현해야 하는 부분' 중, ](https://github.com/BanApp/BeMyPlant_Frontend/issues/12#issuecomment-1732297805)

1. 구현해야 하는 부분 '**1. 식물 이름 설정 후 imageSelect 에 식물 이름 업데이트**' 부분
-> bundle을 통해 fragment간 이동 시 식물 이름을 같이 넘겨 구현했습니다 !
 (plantRegisterFragment.kt, imageSelectFragment.kt 참고)

2. nav_graph 이슈
-> 해당 부분은 새 이슈로 만들겠습니다 ! #24

3. 회원가입 시 * 처리
-> 해당 부분은 새로 이슈를 만들겠습니다! ! #26

---

## 참고사항
###  popup 관련
- 참고로, popup 관련하여 main 화면 -> id card 부분은 팝업 처리하지 않고 cmj2 그대로 갔습니다만, 
UI적으로 혹시 (setting의 popup처럼)주변이 어두워지는 효과가 필요하다면 말씀해주세요! 수정하겠습니다 !
