### ISSUE TITLE
[로직/에러] 식물 삭제 후 nav_graph cannot find 에러 

### ISSUE THREAD

**Issue by 1006lem** [BanApp/BeMyPlant_App#24]
## 관련 이슈 
#12 [[화면연결/로직] 식물신분증 화면 연결]

## 문제
- 식물 삭제 후 
 -> 메인 화면의 (+) 이미지 클릭 시 
 -> PlantRegisterFragment 동작 시  **nav_graph cannot find 에러**

## 해결 사항
- PlantRegisterFragment 이후 nav_graph를 따르도록 에러 수정

**Comment by Minjeongc** [comment]
어 ! 
- 문제점
**nav_graph가 정의되어 있지 않아서** nav_graph를 찾을수 없음.
nav_graph가 **MJ_MainActivity(회원가입, 로그인 클릭하는 창)에 정의 되어 있어서**  (+) 클릭 후, PlantRegisterFragment 실행을 하려면 실행 전에 MJ_MainActivity 실행되어야 함. 
근데, 로그인이 되어 있으면 앱 실행 첫 화면이 MainActivity라 nav_graph가 정의되어 있지 않음. 

- 생각한 해결 방안: nav_graph를 나눔. 
1. 회원가입-sign1-sign2, 로그인-아이디,비밀번호 입력창 부분만. 
2. plantRegister~블루투스 연결창까지

**Comment by 1006lem** [comment]
km2 브랜치에 업로드

## 수정사항 (해결방안)
- nav_graph를 nav_graph와 nav_graph1로 쪼갬
- 쪼갠 nav_graph와 nav_graph1을 위한 nav_host 등록, nav_host를 위한 `activity 등록`  

## 추가된 (해결된) 기능 
- 식물 신분증 -> 식물 이미지 클릭 시 -> 식물 이미지 재선택 
- 메인 화면 내 (+) 클릭 시 -> 식물 이미지 재선택 창 + 블루투스 등록 창 (`nav_graph1`)


## nav_graph

<img width="200" alt="image" src="https://github.com/BanApp/BeMyPlant_Frontend/assets/68532437/f3706110-4be2-4b27-b229-fbf769261fda">

## nav_graph1
![image](https://github.com/BanApp/BeMyPlant_Frontend/assets/68532437/fa45b958-b1b7-4031-9188-715a793f8a42)
