### ISSUE TITLE
[디자인/로직] editText/searchView 수정 

### ISSUE THREAD

**Issue by 1006lem** [BanApp/BeMyPlant_App#26]
## 관련 이슈
- #12에서 제기된 회원가입 - 비밀번호 - editText의 눈 기능

## 구현사항
- [x] 1. 회원가입 (fragment_sign_up2.xml) 
- [x] 2. 로그인 (fragment_login.xml)
- [x] 3. 식물 품종/이름 기입 (fragment_plant_register.xml)
- [x] 4. 로그인 (fragment_login.xml) (**필수사항 X**)

 ### 1. 회원가입 (fragment_sign_up2.xml) 
- 비밀번호, 비밀번호 확인 부분에서 눈 모양 클릭 시 비밀번호 (*) 가 보이도록 구현

### 2. 로그인 (fragment_login.xml)
- 비밀번호 부분에서 눈 모양 클릭 시 비밀번호 (*) 가 보이도록 구현

### 3. 식물 품종/이름 기입 (fragment_plant_register.xml)
- 식물 품종 기입 시 SearchView 로직 구현 

### 4. 로그인 (fragment_login.xml) (**필수사항 X**)
- ID, 비밀번호 기입 시 텍스트가 editText 상자와 맞닿아 있어, 
혹시 사용자가 입력하는 텍스트 ~ editText상자 사이의 거리를 조금 줄 수 있을까요 ? (이건 꼭 구현하지 않아도 될것 같습니다 !!)

**Comment by Minjeongc** [comment]
1,2 -> 수정 완료 
[비밀번호 마스킹.webm](https://github.com/BanApp/BeMyPlant_Frontend/assets/87174310/c3ed86bb-1696-46b5-8182-30aef79678f5)

3 -> fragment_plant_image_select1.xml에서 수정 완료했습니다🙂 
4 -> 회원가입 및 로그인 화면에서 구성들 위치가 이상해서 한번 수정을 해야할거 같아요 다음주에 수정하면서 같이 수정해보겠습니다..🥲
