### ISSUE TITLE
[로직] 환경설정 - 센서 변경 로직 구현

### ISSUE THREAD

**Issue by Minjeongc** [BanApp/BeMyPlant_App#32]
1. 환경설정 내 센서 변경 기능 추가
2. 센서 변경 로직 구현하기 

- nav_graph3 구현하여 서브 내비게이션 생성
- nav_graph에 있던 블루투스 관련 로직 삭제 
<img width="467" alt="image" src="https://github.com/BanApp/BeMyPlant_Frontend/assets/87174310/de541c4c-3ed6-4e3b-827b-2157f5bcee82">

[센서변경로직.webm](https://github.com/BanApp/BeMyPlant_Frontend/assets/87174310/92b9edd2-c8d8-40ec-8fe5-2b768cebe213)

**Comment by 1006lem** [comment]
민정언니 
cmj3 브랜치에서 작업완료 
(**센서변경로직** commit 확인)
