### ISSUE TITLE
[메인] 고쳐야 할 이슈들

### ISSUE THREAD

**Issue by Minjeongc** [BanApp/BeMyPlant_App#33]
**1. 기존** 
- [ ] 신분증 내 식물 이미지 클릭 시 이미지 수정 화면 전환 X
- [ ] UI 크기 수정 (ex. 회원가입 , 로그인, 다음 버튼(가로세로 2.3:1 vs dp지정) 등 자잘자잘한 구성요소들 크기 조절)
- [ ] 식물 삭제시 로직 수정 
- [ ] 이미지 비율 확인, 조정 (다이어리, 식물/사용자 이미지 : 앱 동작 중 받아오는 이미지)

**2. 신규**
- [ ] dalle 연결
- [ ] 메인 화면 내 이미지 뷰 추가하기 (ex. 날씨 )
- [ ] 채팅창 내 식물, 사용자 이미지 추가하기
- [ ] 신분증 -> 식물 이미지 생성 불가하도록 고치기 (nav_graph 현재는 끊어놓을 것)

**Comment by 1006lem** [comment]
가장 최근의 branch : mj5
-> mj5 브랜치를 이은 km3 브랜치에서 작업 (규민) 하겠습니다 !
