### ISSUE TITLE
[화면연결/로직] setting 화면 구성

### ISSUE THREAD

**Issue by 1006lem** [BanApp/BeMyPlant_App#5]
## 민정언니
1. 식물 삭제 시 로직 구현 
- 삭제 버튼 클릭 -> 팝업 (예/아니오) -> 메인화면에 식물이 (+) 형태로 -> 식물 클릭 시 식물 생성 )
- (+) 그림 /res에 추가할 것

###  관련 화면
<img width="120" alt="image" src="https://github.com/BanApp/BeMyPlant_App/assets/68532437/1fd837af-43eb-45b9-8e3a-107f207dee57">

<br>

## 규민
1. 로그아웃, 회원 탈퇴 팝업 처리
- 로그 아웃의 경우 현재 계정 로그아웃 & 쿠키/세션 삭제 후 초기 화면으로 액티비티 연결
- 회원 탈퇴의 경우 rest api로 회원 계정 삭제 & 초기 화면으로 액티비티 연결

2. 사용자 계정 정보 API 백엔드에서 호출

**Comment by Minjeongc** [comment]
1. 식물삭제 이미지 변경 로직 구현 
 - DB와 관련된 식물 정보 삭제하는 부분은 아직 구현 X
 - UI 부분부분 수정 
 - 식물 삭제 -> 이미지 변경 화면 (imageSelect) 에서 문구 수정

[device-2023-09-15-231314.webm](https://github.com/BanApp/BeMyPlant_App/assets/87174310/5ec8f55c-518a-4665-867b-42086d457280)

**Comment by 1006lem** [comment]
## 구현내용
1. 로그아웃, 회원 탈퇴 팝업 처리
- 로그 아웃 -> 로그인 토큰 삭제 후 초기 화면으로 액티비티 연결
- 회원 탈퇴 ->  rest api로 회원 계정 삭제(withdrawal) & 초기 화면으로 액티비티 연결

<br>

2. 사용자 계정 정보 API 백엔드에서 호출
- setting 화면 렌더링 시 사용자 계정 정보 호출 -> (1) 유저 실명, (2) 유저 id 조회 후 렌더링 완료  

<br>

3. (추가) UI 수정
- activity_setting.xml 화면 자잘하게 수정 


---
## 향후 계획

- activity_setting.xml UI 통합 필요
- 팝업 UI & 로직 통합 필요 

---

## 관련 화면

https://github.com/BanApp/BeMyPlant_App/assets/68532437/66557530-85dd-49c9-bf13-9259d0829a16


https://github.com/BanApp/BeMyPlant_App/assets/68532437/63f66f84-a48d-4a90-a0b7-028cc7a94917
