### ISSUE TITLE
[화면구성] 식물 신분증 UI 구성

### ISSUE THREAD

**Issue by 1006lem** [BanApp/BeMyPlant_App#9]
## 관련 화면
<img width="300" alt="image" src="https://github.com/BanApp/BeMyPlant_App/assets/68532437/62909ce1-4984-4ad4-8186-cd860593c6b0">

## 구현 사항
- 식물 신분증 생성
-> 식물 이미지, 식물 이름, 식물 품종, 식물 등록번호 

- 식물 등록번호: 일단 랜덤값으로 생성 (추후 논의)

**Comment by Minjeongc** [comment]
- 파일명(FlowerIdFragment, fragment_flower_id.xml) 으로 만들었습니다!
- 식물이미지(imageView)는 아직 메인화면 식물이랑 연동되어있진 않아요! (이번주 내 수정 예정) 
<img width="370" alt="KakaoTalk_Photo_2023-09-11-17-55-35" src="https://github.com/BanApp/BeMyPlant_App/assets/87174310/0e9df9e3-b71a-46ca-be0d-cf76fed7d2a5">
